---

# Virtualenv settings.
enable_deadsnakes_ppa: no
recreate_virtualenv: no
virtualenv_python_version: "{{ base_python_package }}"


# Application settings.
virtualenv_path: "/webapps/{{ application_name }}"
project_path: "{{ virtualenv_path }}/{{ project_name }}"
django_path: "{{ project_path }}/{{ django_relative_path }}"
application_log_dir: "{{ virtualenv_path }}/logs"
application_log_file: "{{ application_log_dir }}/gunicorn_supervisor.log"
requirements_file: "{{ project_path }}/{{ requirements_relative_file }}"


# Gunicorn settings.
gunicorn_user: "{{ application_name }}"
gunicorn_group: webapps


# Nginx settings.
nginx_access_log_file: "{{ application_log_dir }}/nginx_access.log"
nginx_error_log_file: "{{ application_log_dir }}/nginx_error.log"
nginx_static_dir: "{{ virtualenv_path }}/static/"
nginx_media_dir: "{{ virtualenv_path }}/media/"


# Django environment variables.
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  MEDIA_ROOT: "{{ nginx_media_dir }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_NAME: "{{ db_name }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  BROKER_URL: "{{ broker_url }}"
